# Generated by Django 4.2.7 on 2025-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('nacionalidade', models.CharField(blank=True, default='Brasileiro', max_length=50)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20)),
                ('profissao', models.CharField(blank=True, default='Outros', max_length=100)),
                ('pontuacao_score', models.IntegerField(blank=True, default=0, null=True)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fonte_lead', models.CharField(choices=[('INDICACOES', 'Indicações'), ('CAPTADORES', 'Captadores'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('KWAI', 'Kwai'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50)),
                ('cadastro_completo', models.BooleanField(default=False)),
                ('ficha_associativa', models.BooleanField(default=False)),
                ('boletos_enviados', models.BooleanField(default=False)),
                ('primeiro_levantamento', models.BooleanField(default=False)),
                ('documentacao_coletada', models.BooleanField(default=False)),
                ('cliente_app', models.BooleanField(default=False)),
                ('nada_consta_entregue', models.BooleanField(default=False)),
                ('segundo_levantamento', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('captador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_captados', to=settings.AUTH_USER_MODEL)),
                ('consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_consultor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('ATENDIMENTO', 'Atendimento'), ('ALTERACAO', 'Alteração Cadastral'), ('PAGAMENTO', 'Pagamento'), ('DOCUMENTO', 'Documento'), ('OUTRO', 'Outro')], default='ATENDIMENTO', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do Cliente',
                'verbose_name_plural': 'Históricos dos Clientes',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='clientes_cl_cpf_e6905f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['fonte_lead'], name='clientes_cl_fonte_l_48dfbf_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['consultor'], name='clientes_cl_consult_a90f50_idx'),
        ),
    ]
