# Generated by Django 4.2.7 on 2025-10-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_lead_cpf_cnpj'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicocliente',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_cpf_e6905f_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_fonte_l_48dfbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_consult_a90f50_idx',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='asaas_customer_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fonte_lead',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='marketing.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricoCliente',
        ),
    ]
