# Generated by Django 4.2.7 on 2025-10-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_historicocliente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=50),
        ),
    ]
