# Generated by Django 4.2.7 on 2025-10-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileiro(a)', max_length=50),
        ),
    ]
