# Generated by Django 4.2.7 on 2025-10-30 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0004_alter_cliente_nacionalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario_portal',
            field=models.OneToOneField(blank=True, help_text='Usuário criado automaticamente para acesso à área do cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_portal', to=settings.AUTH_USER_MODEL),
        ),
    ]
