# Generated by Django 4.2.7 on 2025-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_usuario_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='Inscrição Municipal (necessário para PJ prestador de serviço)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Razão Social (obrigatório para CNPJ)', max_length=200, null=True),
        ),
    ]
