# Generated by Django 4.2.7 on 2025-10-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('assinatura_gov', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3)),
                ('data_envio_contrato', models.DateField(auto_now_add=True)),
                ('data_assinatura_cliente', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('arquivo_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos_legais/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.contrato')),
            ],
        ),
    ]
