# Generated by Django 4.2.7 on 2025-10-15 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0002_prevenda_documentovenda'),
        ('clientes', '0002_remove_historicocliente_cliente_and_more'),
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='documentolegal',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Documento Legal', 'verbose_name_plural': 'Documentos Legais'},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_assinatura_cliente',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_envio_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='arquivo_assinado',
            field=models.FileField(blank=True, null=True, upload_to='contratos/assinados/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='assinatura_manual',
            field=models.BooleanField(default=False, verbose_name='Assinatura Manual'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_geracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario_geracao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_gerados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='venda',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='vendas.venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentolegal',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentolegal',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato'), ('PROCURACAO', 'Procuração'), ('REQUERIMENTO', 'Requerimento'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='documentolegal',
            name='usuario_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='assinatura_gov',
            field=models.BooleanField(default=False, verbose_name='Assinatura Gov.br'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_GERACAO', 'Aguardando Geração'), ('GERADO', 'Gerado'), ('ENVIADO', 'Enviado ao Cliente'), ('ASSINADO', 'Assinado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_GERACAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentolegal',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='juridico.contrato'),
        ),
    ]
