# Generated by Django 4.2.7 on 2025-10-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_GERACAO', 'Aguardando Geração'), ('GERADO', 'Gerado - Pendente Assinatura'), ('ENVIADO', 'Enviado ao Cliente'), ('ASSINADO', 'Assinado pelo Cliente'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_GERACAO', max_length=30),
        ),
    ]
