# Generated by Django 4.2.7 on 2025-10-29 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0004_alter_cliente_nacionalidade'),
        ('vendas', '0007_repescagemlead_historicorepescagem_and_more'),
        ('juridico', '0004_alter_contrato_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_distrato', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('TENTATIVA_ACORDO', 'Tentativa de Acordo'), ('ACORDO_RECUSADO', 'Acordo Recusado'), ('MULTA_GERADA', 'Multa Gerada'), ('MULTA_PAGA', 'Multa Paga'), ('MULTA_VENCIDA', 'Multa Vencida'), ('ENVIADO_JURIDICO', 'Enviado ao Jurídico'), ('CANCELADO', 'Cancelado')], default='TENTATIVA_ACORDO', max_length=30)),
                ('tentativa_acordo', models.BooleanField(default=True, verbose_name='Tentou acordo?')),
                ('acordo_aceito', models.BooleanField(default=False, verbose_name='Acordo aceito?')),
                ('detalhes_acordo', models.TextField(blank=True, verbose_name='Detalhes da tentativa de acordo')),
                ('valor_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_vencimento_multa', models.DateField(blank=True, null=True)),
                ('data_pagamento_multa', models.DateField(blank=True, null=True)),
                ('boleto_multa_codigo', models.CharField(blank=True, max_length=100)),
                ('arquivo_distrato', models.FileField(blank=True, null=True, upload_to='distratos/')),
                ('arquivo_boleto_multa', models.FileField(blank=True, null=True, upload_to='distratos/boletos/')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_tentativa_acordo', models.DateTimeField(blank=True, null=True)),
                ('data_recusa_acordo', models.DateTimeField(blank=True, null=True)),
                ('data_geracao_multa', models.DateTimeField(blank=True, null=True)),
                ('data_envio_juridico', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('historico', models.JSONField(blank=True, default=list)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distratos', to='clientes.cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distratos', to='juridico.contrato')),
                ('usuario_solicitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distratos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distratos', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Distrato',
                'verbose_name_plural': 'Distratos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(blank=True, max_length=50, unique=True)),
                ('tipo_processo', models.CharField(choices=[('DISTRATO', 'Distrato Contratual'), ('COBRANCA', 'Cobrança Judicial'), ('OUTROS', 'Outros')], default='DISTRATO', max_length=20)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura Cliente'), ('ASSINADO', 'Assinado pelo Cliente'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='EM_ANDAMENTO', max_length=30)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_envio_juridico', models.DateTimeField(blank=True, null=True)),
                ('data_assinatura_cliente', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('assinatura_cliente', models.BooleanField(default=False)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='processos/assinados/')),
                ('arquivo_processo', models.FileField(blank=True, null=True, upload_to='processos/')),
                ('observacoes', models.TextField(blank=True)),
                ('historico', models.JSONField(blank=True, default=list)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_juridicos', to='clientes.cliente')),
                ('distrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo_juridico', to='juridico.distrato')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_juridicos', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Processo Jurídico',
                'verbose_name_plural': 'Processos Jurídicos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
