# Generated by Django 4.2.7 on 2025-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0005_distrato_processojuridico'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrato',
            name='boleto_multa_linha_digitavel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Linha Digitável'),
        ),
        migrations.AddField(
            model_name='distrato',
            name='boleto_multa_url',
            field=models.URLField(blank=True, verbose_name='URL Boleto ASAAS'),
        ),
        migrations.AlterField(
            model_name='distrato',
            name='boleto_multa_codigo',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Boleto ASAAS'),
        ),
    ]
