# Generated by Django 4.2.7 on 2025-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosusuario',
            name='contato_recado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='id_captador',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='id_consultor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='quantidade_clientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='total_comissao_recebida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='total_vendas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dadosusuario',
            name='whatsapp_pessoal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='conta_bancaria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco_completo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
