# Generated by Django 4.2.7 on 2025-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dadosusuario_contato_recado_dadosusuario_id_captador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
