# Generated by Django 4.2.7 on 2025-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('id_asaas', models.CharField(blank=True, max_length=100)),
                ('url_boleto', models.URLField(blank=True)),
                ('codigo_barras', models.TextField(blank=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoPIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('asaas_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_code', models.TextField(blank=True, null=True)),
                ('pix_qr_code_url', models.TextField(blank=True, null=True)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_calculada', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='pendente', max_length=20)),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.parcela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
    ]
