# Generated by Django 4.2.7 on 2025-10-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_lead_cpf_cnpj'),
        ('financeiro', '0002_pixlevantamento_clienteasaas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteasaas',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='clienteasaas',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clienteasaas',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='clienteasaas',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='clienteasaas',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='clienteasaas',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas', to='marketing.lead'),
        ),
    ]
