# Generated by Django 4.2.7 on 2025-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_clienteasaas_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixlevantamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=20),
        ),
    ]
