# Generated by Django 4.2.7 on 2025-10-15 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0002_prevenda_documentovenda'),
        ('financeiro', '0004_alter_pixlevantamento_status_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissao',
            options={'ordering': ['-data_calculada'], 'verbose_name': 'Comissão de Venda', 'verbose_name_plural': 'Comissões de Vendas'},
        ),
        migrations.AddField(
            model_name='comissao',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Detalhes do cálculo (faturamento mensal, escala, etc)'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='tipo_comissao',
            field=models.CharField(choices=[('CAPTADOR_ENTRADA', 'Captador - Entrada'), ('CAPTADOR_PARCELA', 'Captador - Parcela'), ('CONSULTOR_ENTRADA', 'Consultor - Entrada'), ('CONSULTOR_PARCELA', 'Consultor - Parcela')], default='CAPTADOR_ENTRADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='financeiro.parcela'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, help_text='Percentual aplicado no momento do cálculo', max_digits=5),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_venda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='vendas.venda'),
        ),
        migrations.AddIndex(
            model_name='comissao',
            index=models.Index(fields=['usuario', 'data_calculada'], name='financeiro__usuario_8e4bba_idx'),
        ),
        migrations.AddIndex(
            model_name='comissao',
            index=models.Index(fields=['venda', 'tipo_comissao'], name='financeiro__venda_i_27789c_idx'),
        ),
        migrations.AddIndex(
            model_name='comissao',
            index=models.Index(fields=['status', 'data_calculada'], name='financeiro__status_88135f_idx'),
        ),
    ]
