# Generated by Django 4.2.7 on 2025-10-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_comissao_options_comissao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['venda', 'numero_parcela'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_envio_asaas',
            field=models.DateTimeField(blank=True, help_text='Data/hora do envio para ASAAS', null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='enviado_asaas',
            field=models.BooleanField(default=False, help_text='Indica se a cobrança foi enviada para o ASAAS'),
        ),
    ]
