# Generated by Django 4.2.7 on 2025-10-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_motivorecusa_alter_prevenda_motivo_recusa_and_more'),
        ('financeiro', '0006_alter_parcela_options_parcela_data_envio_asaas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_payment_id', models.CharField(max_length=255, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pix_code', models.TextField(help_text='Código copia e cola do PIX')),
                ('pix_qr_code_url', models.TextField(help_text='URL da imagem do QR Code')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_entradas', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'PIX de Entrada',
                'verbose_name_plural': 'PIX de Entradas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
