# Generated by Django 4.2.7 on 2025-10-29 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_repescagemlead_historicorepescagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0007_pixentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_renegociacao', models.CharField(choices=[('desconto', 'Desconto sobre Parcelas'), ('nova_parcela', 'Nova Parcelamento'), ('prorrogacao', 'Prorrogação de Vencimento'), ('combinada', 'Renegociação Combinada')], default='desconto', max_length=20)),
                ('valor_total_divida', models.DecimalField(decimal_places=2, help_text='Valor total da dívida original', max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, help_text='Valor de desconto concedido', max_digits=10)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, help_text='% de desconto', max_digits=5)),
                ('valor_novo_total', models.DecimalField(decimal_places=2, help_text='Novo valor total após negociação', max_digits=10)),
                ('numero_novas_parcelas', models.IntegerField(default=1, help_text='Quantidade de novas parcelas')),
                ('data_primeira_parcela', models.DateField(help_text='Vencimento da primeira parcela renegociada')),
                ('status', models.CharField(choices=[('em_negociacao', 'Em Negociação'), ('aceita', 'Aceita pelo Cliente'), ('recusada', 'Recusada pelo Cliente'), ('efetivada', 'Efetivada no ASAAS'), ('cancelada', 'Cancelada')], default='em_negociacao', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a negociação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_efetivacao', models.DateTimeField(blank=True, help_text='Quando a renegociação foi efetivada no ASAAS', null=True)),
                ('asaas_ids_cancelados', models.TextField(blank=True, help_text='IDs das cobranças canceladas no ASAAS (JSON)')),
                ('asaas_ids_novos', models.TextField(blank=True, help_text='IDs das novas cobranças no ASAAS (JSON)')),
                ('parcelas_original', models.ManyToManyField(blank=True, related_name='renegociacoes_original', to='financeiro.parcela')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renegociacoes_financeiro', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renegociacoes', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Renegociação',
                'verbose_name_plural': 'Renegociações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoContatoRetencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[('telefone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('sms', 'SMS')], max_length=20)),
                ('resultado', models.CharField(choices=[('contato_sucesso', 'Contato com Sucesso'), ('nao_atendeu', 'Não Atendeu'), ('promessa_pagamento', 'Promessa de Pagamento'), ('negociacao_iniciada', 'Negociação Iniciada'), ('recusa_negociacao', 'Recusa de Negociação'), ('numero_invalido', 'Número Inválido')], max_length=30)),
                ('observacoes', models.TextField(help_text='Detalhes do contato')),
                ('data_contato', models.DateTimeField(auto_now_add=True)),
                ('data_proxima_tentativa', models.DateField(blank=True, help_text='Agendamento para próximo contato', null=True)),
                ('renegociacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='financeiro.renegociacao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_retencao', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_retencao', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Histórico de Contato - Retenção',
                'verbose_name_plural': 'Históricos de Contato - Retenção',
                'ordering': ['-data_contato'],
            },
        ),
    ]
