# Generated by Django 4.2.7 on 2025-10-30 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCurto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Código Curto')),
                ('url_completa', models.URLField(max_length=500, verbose_name='URL Completa')),
                ('total_cliques', models.IntegerField(default=0, verbose_name='Total de Cliques')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('captador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_curto', to=settings.AUTH_USER_MODEL, verbose_name='Captador')),
            ],
            options={
                'verbose_name': 'Link Curto',
                'verbose_name_plural': 'Links Curtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClickLinkCurto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, null=True, verbose_name='Referência')),
                ('clicado_em', models.DateTimeField(auto_now_add=True, verbose_name='Clicado em')),
                ('link_curto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliques', to='captadores.linkcurto', verbose_name='Link Curto')),
            ],
            options={
                'verbose_name': 'Clique em Link Curto',
                'verbose_name_plural': 'Cliques em Links Curtos',
                'ordering': ['-clicado_em'],
            },
        ),
    ]
