# Generated by Django 4.2.7 on 2025-11-04 09:56

import captadores.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Material')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('PDF', 'PDF'), ('OUTRO', 'Outro')], default='IMAGEM', max_length=20, verbose_name='Tipo de Material')),
                ('arquivo', models.FileField(upload_to=captadores.models.material_upload_path, verbose_name='Arquivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='materiais_divulgacao/thumbnails/', verbose_name='Miniatura')),
                ('tamanho', models.IntegerField(default=0, help_text='Tamanho do arquivo em bytes', verbose_name='Tamanho')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Materiais com menor número aparecem primeiro', verbose_name='Ordem de Exibição')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Material de Divulgação',
                'verbose_name_plural': 'Materiais de Divulgação',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
