# Generated by Django 4.2.7 on 2025-10-08 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('BOOLEANO', 'Booleano'), ('JSON', 'JSON')], default='TEXTO', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('mensagem', models.TextField()),
                ('modulo', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('AVISO', 'Aviso'), ('INFO', 'Informação')], default='INFO', max_length=10)),
                ('lida', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['modulo', 'acao'], name='core_logsis_modulo_547325_idx'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['data_criacao'], name='core_logsis_data_cr_937c2d_idx'),
        ),
    ]
