# Generated by Django 4.2.7 on 2025-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaosistema_logsistema_notificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
