# Generated by Django 4.2.7 on 2025-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaosistema_ultima_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASAAS', 'ASAAS'), ('OUTRO', 'Outro')], default='ASAAS', max_length=20, verbose_name='Tipo')),
                ('evento', models.CharField(blank=True, max_length=100, verbose_name='Evento')),
                ('payload', models.JSONField(verbose_name='Payload Completo')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Headers HTTP')),
                ('status_processamento', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Erro'), ('IGNORED', 'Ignorado')], max_length=20, verbose_name='Status')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Payment ID')),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Customer ID')),
                ('payment_status', models.CharField(blank=True, max_length=50, verbose_name='Status Pagamento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Origem')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data Recebimento')),
                ('processado_em', models.DateTimeField(auto_now=True, verbose_name='Processado em')),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhooks',
                'db_table': 'core_webhook_log',
                'ordering': ['-data_recebimento'],
                'indexes': [models.Index(fields=['-data_recebimento'], name='core_webhoo_data_re_076cca_idx'), models.Index(fields=['payment_id'], name='core_webhoo_payment_0414c8_idx'), models.Index(fields=['evento'], name='core_webhoo_evento_39ed8c_idx')],
            },
        ),
    ]
