# Generated by Django 4.2.7 on 2025-11-02 16:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0010_venda_cliente_quer_nf_venda_nf_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='CNPJ da empresa (formato: 00.000.000/0000-00)', max_length=18)),
                ('razao_social', models.CharField(help_text='Razão Social da empresa', max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome Fantasia', max_length=200)),
                ('inscricao_municipal', models.CharField(help_text='Inscrição Municipal', max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, help_text='Inscrição Estadual (se aplicável)', max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('regime_tributario', models.CharField(default='Simples Nacional', help_text='Regime Tributário', max_length=50)),
                ('aliquota_iss_padrao', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Alíquota de ISS padrão (%)', max_digits=5)),
                ('codigo_servico_padrao', models.CharField(default='01.01', help_text='Código de serviço padrão (LC 116/2003)', max_length=10)),
                ('descricao_servico_padrao', models.TextField(default='Consultoria Financeira e Assessoria em Crédito', help_text='Descrição padrão do serviço')),
                ('email_remetente', models.EmailField(help_text='E-mail remetente das notas fiscais', max_length=254)),
                ('emissao_automatica', models.BooleanField(default=True, help_text='Emitir notas automaticamente após pagamento confirmado')),
                ('envio_automatico_email', models.BooleanField(default=True, help_text='Enviar e-mail automaticamente após emissão')),
                ('prazo_cancelamento_horas', models.IntegerField(default=24, help_text='Prazo em horas para cancelamento da NF')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Fiscal',
                'verbose_name_plural': 'Configurações Fiscais',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PARCELA', 'Parcela')], help_text='Tipo da nota fiscal', max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Emissão'), ('EM_PROCESSAMENTO', 'Processando'), ('EMITIDA', 'Emitida'), ('ENVIADA', 'Enviada por E-mail'), ('ERRO', 'Erro na Emissão'), ('CANCELADA', 'Cancelada')], default='PENDENTE', help_text='Status atual da nota fiscal', max_length=20)),
                ('id_nf_asaas', models.CharField(blank=True, help_text='ID da nota fiscal no Asaas', max_length=100)),
                ('numero_nf', models.CharField(blank=True, help_text='Número da nota fiscal', max_length=20)),
                ('serie_nf', models.CharField(blank=True, default='1', help_text='Série da nota fiscal', max_length=10)),
                ('codigo_verificacao', models.CharField(blank=True, help_text='Código de verificação da NF', max_length=50)),
                ('chave_acesso', models.CharField(blank=True, help_text='Chave de acesso de 44 dígitos', max_length=44)),
                ('url_pdf', models.URLField(blank=True, help_text='URL do PDF da nota fiscal')),
                ('url_xml', models.URLField(blank=True, help_text='URL do XML da nota fiscal')),
                ('valor_servico', models.DecimalField(decimal_places=2, help_text='Valor do serviço prestado', max_digits=10)),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Alíquota de ISS em porcentagem', max_digits=5)),
                ('valor_iss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do ISS calculado', max_digits=10)),
                ('descricao_servico', models.TextField(blank=True, help_text='Descrição detalhada do serviço prestado')),
                ('codigo_servico_municipal', models.CharField(blank=True, default='01.01', help_text='Código do serviço conforme LC 116/2003', max_length=10)),
                ('tentativas_emissao', models.IntegerField(default=0, help_text='Número de tentativas de emissão')),
                ('mensagem_erro', models.TextField(blank=True, help_text='Mensagem de erro da última tentativa')),
                ('log_integracao', models.JSONField(blank=True, default=dict, help_text='Log completo das integrações com Asaas')),
                ('data_cancelamento', models.DateTimeField(blank=True, help_text='Data de cancelamento da nota', null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, help_text='Motivo do cancelamento')),
                ('email_enviado', models.BooleanField(default=False, help_text='Indica se o e-mail com a NF foi enviado')),
                ('data_envio_email', models.DateTimeField(blank=True, help_text='Data de envio do e-mail', null=True)),
                ('email_destinatario', models.EmailField(blank=True, help_text='E-mail para qual a NF foi enviada', max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
                ('data_emissao', models.DateTimeField(blank=True, help_text='Data de emissão efetiva da nota', null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('cancelada_por', models.ForeignKey(blank=True, help_text='Usuário que cancelou a nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(blank=True, help_text='Parcela específica (se não for entrada)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='vendas.parcela')),
                ('venda', models.ForeignKey(help_text='Venda vinculada à nota fiscal', on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['status', '-data_criacao'], name='notas_fisca_status_2846b2_idx'), models.Index(fields=['venda', 'tipo'], name='notas_fisca_venda_i_493d71_idx'), models.Index(fields=['numero_nf'], name='notas_fisca_numero__ae0ce6_idx')],
            },
        ),
    ]
