# Generated by Django 4.2.7 on 2025-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fonte_lead', models.CharField(choices=[('INDICACAO', 'Indicação'), ('CAPTADOR', 'Captador'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('KWAI', 'Kwai')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido'), ('NAO_INTERESSADO', 'Não Interessado')], default='NOVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('captador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_captados', to=settings.AUTH_USER_MODEL)),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
