# Generated by Django 4.2.7 on 2025-10-09 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='data_criacao',
            new_name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fonte_lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='origem',
            field=models.CharField(choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('LIGACAO', 'Ligação'), ('EVENTO', 'Evento'), ('REDES_SOCIAIS', 'Redes Sociais'), ('OUTRO', 'Outro')], default='SITE', max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='captador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_captados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='consultor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_consultoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nome_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('CONTATADO', 'Contatado'), ('INTERESSADO', 'Interessado'), ('QUALIFICADO', 'Qualificado'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=15),
        ),
    ]
