# Generated by Django 4.2.7 on 2025-10-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Motivo',
                'verbose_name_plural': 'Categorias de Motivo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OrigemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Origem de Contato',
                'verbose_name_plural': 'Origens de Contato',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MotivoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTIVO', 'Motivo'), ('PERFIL', 'Perfil Emocional')], max_length=10)),
                ('texto', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.categoriamotivo')),
            ],
            options={
                'verbose_name': 'Motivo de Contato',
                'verbose_name_plural': 'Motivos de Contato',
                'ordering': ['categoria', 'tipo', 'ordem'],
                'unique_together': {('categoria', 'tipo', 'texto')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='motivo_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MOTIVO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_motivo', to='marketing.motivocontato'),
        ),
        migrations.AddField(
            model_name='lead',
            name='origem_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.origemcontato'),
        ),
        migrations.AddField(
            model_name='lead',
            name='perfil_emocional',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PERFIL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_perfil', to='marketing.motivocontato'),
        ),
    ]
