# Generated by Django 4.2.7 on 2025-10-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_categoriamotivo_origemcontato_motivocontato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Origem de Lead',
                'verbose_name_plural': 'Origens de Lead',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='origem_contato',
        ),
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.origemlead'),
        ),
    ]
