# Generated by Django 4.2.7 on 2025-10-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_pixlevantamento_clienteasaas'),
        ('marketing', '0004_origemlead_remove_lead_origem_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cliente_asaas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_asaas_marketing', to='financeiro.clienteasaas'),
        ),
    ]
