# Generated by Django 4.2.7 on 2025-10-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_clienteasaas_cpf_cnpj_and_more'),
        ('marketing', '0006_lead_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='cliente_asaas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_associados', to='financeiro.clienteasaas'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('CONTATADO', 'Contatado'), ('INTERESSADO', 'Interessado'), ('LEVANTAMENTO_PENDENTE', 'Levantamento Pendente'), ('LEVANTAMENTO_PAGO', 'Levantamento Pago'), ('QUALIFICADO', 'Qualificado'), ('CONTRATADO', 'Contratado'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=25),
        ),
    ]
