# Generated by Django 4.2.7 on 2025-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_lead_options_alter_lead_cliente_asaas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fez_levantamento',
            field=models.BooleanField(default=False, help_text='Indica se o lead pagou o levantamento.'),
        ),
    ]
