# Generated by Django 4.2.7 on 2025-10-13 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0008_lead_fez_levantamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='captador',
            field=models.ForeignKey(blank=True, help_text='Usuário que indicou o serviço (captador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_captados', to=settings.AUTH_USER_MODEL),
        ),
    ]
