# Generated by Django 4.2.7 on 2025-10-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0009_alter_lead_captador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='consultor',
        ),
        migrations.AddField(
            model_name='lead',
            name='atendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_atendimento', to=settings.AUTH_USER_MODEL),
        ),
    ]
