# Generated by Django 4.2.7 on 2025-10-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_remove_lead_consultor_lead_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='passou_compliance',
            field=models.BooleanField(default=False, help_text='Indica se o lead já passou pela análise de Compliance e foi aprovado para pré-venda.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('CONTATADO', 'Contatado'), ('INTERESSADO', 'Interessado'), ('LEVANTAMENTO_PENDENTE', 'Levantamento Pendente'), ('LEVANTAMENTO_PAGO', 'Levantamento Pago'), ('EM_COMPLIANCE', 'Em Análise Compliance'), ('APROVADO_COMPLIANCE', 'Aprovado - Aguardando Consultor'), ('QUALIFICADO', 'Qualificado'), ('CONTRATADO', 'Contratado'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=25),
        ),
    ]
