# Generated by Django 4.2.7 on 2025-10-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_lead_passou_compliance_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='numero_repescagens',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de vezes que este lead foi enviado ao Comercial 2 (repescagem)'),
        ),
    ]
