# Generated by Django 4.2.7 on 2025-11-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_lead_numero_repescagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento do lead (opcional)', null=True),
        ),
    ]
