# Generated by Django 4.2.7 on 2025-10-29 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0007_repescagemlead_historicorepescagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0004_alter_cliente_nacionalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('sms', 'SMS'), ('presencial', 'Presencial')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Canal de Comunicação',
                'verbose_name_plural': 'Canais de Comunicação',
            },
        ),
        migrations.CreateModel(
            name='InteracaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('boas_vindas', 'Boas-vindas'), ('followup', 'Follow-up'), ('cobranca', 'Cobrança'), ('suporte', 'Suporte'), ('pesquisa', 'Pesquisa de Satisfação'), ('aniversario', 'Aniversário'), ('indicacao', 'Solicitação de Indicação'), ('atualizacao', 'Atualização de Status'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('sem_resposta', 'Sem Resposta')], default='agendada', max_length=20)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('data_realizada', models.DateTimeField(blank=True, null=True)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('resposta_cliente', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacionamento.canalcomunicacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Interação com Cliente',
                'verbose_name_plural': 'Interações com Clientes',
                'ordering': ['-data_agendada', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_totais', models.IntegerField(default=0)),
                ('pontos_disponiveis', models.IntegerField(default=0)),
                ('pontos_utilizados', models.IntegerField(default=0)),
                ('nivel', models.CharField(default='Bronze', help_text='Bronze, Prata, Ouro, Diamante', max_length=50)),
                ('total_indicacoes', models.IntegerField(default=0)),
                ('total_vendas_geradas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidade', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Programa de Fidelidade',
                'verbose_name_plural': 'Programas de Fidelidade',
            },
        ),
        migrations.CreateModel(
            name='PesquisaSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_atendimento', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='1-10', null=True)),
                ('nota_produto', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='1-10', null=True)),
                ('nota_geral', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='1-10', null=True)),
                ('recomendaria', models.BooleanField(blank=True, help_text='Recomendaria a empresa?', null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='clientes.cliente')),
                ('interacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='relacionamento.interacaocliente')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Pesquisa de Satisfação',
                'verbose_name_plural': 'Pesquisas de Satisfação',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('pontos', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fidelidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='relacionamento.programafidelidade')),
            ],
            options={
                'verbose_name': 'Movimentação de Pontos',
                'verbose_name_plural': 'Movimentações de Pontos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_indicado', models.CharField(max_length=200)),
                ('telefone_indicado', models.CharField(max_length=20)),
                ('email_indicado', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('contatado', 'Contatado'), ('agendado', 'Agendado'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to='clientes.cliente')),
                ('venda_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao_origem', to='vendas.venda')),
                ('venda_indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
