# Generated by Django 4.2.7 on 2025-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('motivo_principal', models.CharField(choices=[('CONSEGUIR_EMPREGO', 'Conseguir Emprego'), ('ALUGAR_IMOVEL', 'Alugar um Imóvel'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('COMPRA_PARCELADA', 'Compra Parcelada'), ('EMPRESTIMO', 'Empréstimo'), ('ABRIR_EMPRESA', 'Abrir Empresa'), ('TROCA_CARRO', 'Troca de Carro'), ('VIAGEM', 'Viagem')], max_length=50)),
                ('perfil_emocional', models.CharField(choices=[('DESESPERANCA_URGENCIA', 'Desesperança/Urgência'), ('PRESSAO_ESTABILIDADE', 'Pressão por Estabilidade'), ('IMPULSIVIDADE_CONSUMO', 'Impulsividade/Consumo'), ('CONSUMO_IMEDIATO', 'Consumo Imediato'), ('DESESPERO_INSTABILIDADE', 'Desespero/Instabilidade'), ('PLANEJAMENTO_INICIAL', 'Planejamento Inicial'), ('CONSCIENCIA_RECUPERACAO', 'Consciência/Recuperação'), ('PLANEJADOR_ANSIOSO', 'Planejador/Ansioso')], max_length=50)),
                ('tipo_servico_interesse', models.CharField(choices=[('LIMPA_NOME', 'Limpa Nome'), ('RETIRADA_TRAVAS', 'Retirada de Travas'), ('RECUPERACAO_SCORE', 'Recuperação de Score'), ('LIMPA_NOME_RETIRADA_TRAVAS', 'Limpa Nome + Retirada de Travas'), ('RECUPERACAO_SCORE_LIMPA_NOME', 'Recuperação Score + Limpa Nome'), ('RECUPERACAO_SCORE_RETIRADA_TRAVAS', 'Recuperação Score + Retirada Travas'), ('COMPLETO', 'Completo')], max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.lead')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
