# Generated by Django 4.2.7 on 2025-10-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Motivo',
                'verbose_name_plural': 'Categorias de Motivo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OrigemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Origem de Contato',
                'verbose_name_plural': 'Origens de Contato',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MotivoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTIVO', 'Motivo'), ('PERFIL', 'Perfil Emocional')], max_length=10)),
                ('texto', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.categoriamotivo')),
            ],
            options={
                'verbose_name': 'Motivo de Contato',
                'verbose_name_plural': 'Motivos de Contato',
                'ordering': ['categoria', 'tipo', 'ordem'],
                'unique_together': {('categoria', 'tipo', 'texto')},
            },
        ),
        migrations.CreateModel(
            name='AtendimentoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('valor_consulta', models.DecimalField(decimal_places=2, default=29.9, max_digits=10)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100)),
                ('pix_code', models.TextField(blank=True)),
                ('pix_qr_code', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago - Pronto para Levantamento'), ('LEVANTAMENTO_ENVIADO', 'Levantamento Enviado'), ('CANCELADO', 'Cancelado')], default='NOVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(limit_choices_to={'tipo': 'MOTIVO'}, on_delete=django.db.models.deletion.PROTECT, to='atendimento.motivocontato')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.origemcontato')),
                ('perfil_emocional', models.ForeignKey(limit_choices_to={'tipo': 'PERFIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_emocional_atendimentos', to='atendimento.motivocontato')),
            ],
            options={
                'verbose_name': 'Atendimento Inicial',
                'verbose_name_plural': 'Atendimentos Iniciais',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_inicial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendimentoinicial'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='motivo_principal',
            field=models.ForeignKey(limit_choices_to={'tipo': 'MOTIVO'}, on_delete=django.db.models.deletion.PROTECT, related_name='motivo_atendimentos', to='atendimento.motivocontato'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='perfil_emocional',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PERFIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_atendimentos', to='atendimento.motivocontato'),
        ),
    ]
