# Generated by Django 4.2.7 on 2025-10-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_lead_options_and_more'),
        ('atendimento', '0003_dados_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='marketing.lead'),
        ),
    ]
