# Generated by Django 4.2.7 on 2025-10-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_categoriamotivo_origemcontato_motivocontato_and_more'),
        ('atendimento', '0004_alter_atendimento_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motivocontato',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='motivocontato',
            name='categoria',
        ),
        migrations.AddField(
            model_name='atendimentoinicial',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_iniciais', to='marketing.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='motivo_principal',
            field=models.ForeignKey(limit_choices_to={'tipo': 'MOTIVO'}, on_delete=django.db.models.deletion.PROTECT, related_name='motivo_atendimentos', to='marketing.motivocontato'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='perfil_emocional',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PERFIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_atendimentos', to='marketing.motivocontato'),
        ),
        migrations.AlterField(
            model_name='atendimentoinicial',
            name='motivo',
            field=models.ForeignKey(limit_choices_to={'tipo': 'MOTIVO'}, on_delete=django.db.models.deletion.PROTECT, to='marketing.motivocontato'),
        ),
        migrations.AlterField(
            model_name='atendimentoinicial',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.origemcontato'),
        ),
        migrations.AlterField(
            model_name='atendimentoinicial',
            name='perfil_emocional',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PERFIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_emocional_atendimentos', to='marketing.motivocontato'),
        ),
        migrations.DeleteModel(
            name='CategoriaMotivo',
        ),
        migrations.DeleteModel(
            name='MotivoContato',
        ),
        migrations.DeleteModel(
            name='OrigemContato',
        ),
    ]
