# Generated by Django 4.2.7 on 2025-10-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_alter_motivocontato_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='atendimento_inicial',
        ),
        migrations.DeleteModel(
            name='AtendimentoInicial',
        ),
    ]
