# Generated by Django 4.2.7 on 2025-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaasclientesyncronizado',
            name='consultor_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Consultor Responsável'),
        ),
        migrations.AddField(
            model_name='asaasclientesyncronizado',
            name='servico_concluido',
            field=models.BooleanField(default=False, verbose_name='Serviço Concluído'),
        ),
    ]
