# Generated by Django 4.2.7 on 2025-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_sync', '0002_asaasclientesyncronizado_consultor_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaassyncronizacaolog',
            name='tipo_sincronizacao',
            field=models.CharField(choices=[('COMPLETO', 'Sincronização Completa'), ('BOLETOS_FALTANTES', 'Boletos Faltantes'), ('ALTERNATIVO', 'Sincronização Alternativa')], default='COMPLETO', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='asaassyncronizacaolog',
            name='status',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial'), ('EM_ANDAMENTO', 'Em Andamento')], max_length=20, verbose_name='Status'),
        ),
    ]
