# Generated by Django 4.2.7 on 2025-11-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_sync', '0003_asaassyncronizacaolog_tipo_sincronizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaasclientesyncronizado',
            name='servico_limpa_nome',
            field=models.BooleanField(default=False, verbose_name='Limpa Nome'),
        ),
        migrations.AddField(
            model_name='asaasclientesyncronizado',
            name='servico_restauracao_score',
            field=models.BooleanField(default=False, verbose_name='Restauração de Score'),
        ),
        migrations.AddField(
            model_name='asaasclientesyncronizado',
            name='servico_retirada_travas',
            field=models.BooleanField(default=False, verbose_name='Retirada de Travas'),
        ),
    ]
