# Generated by Django 4.2.7 on 2025-11-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_sync', '0004_asaasclientesyncronizado_servico_limpa_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoClienteAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('CNH', 'CNH'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('CONTRATO', 'Contrato'), ('PROCURACAO', 'Procuração'), ('CARTA_AUTORIZACAO', 'Carta de Autorização'), ('EXTRATO_BANCARIO', 'Extrato Bancário'), ('RELATORIO', 'Relatório'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='asaas_clientes_docs/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('tamanho_original', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho Original (bytes)')),
                ('tamanho_final', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho Final (bytes)')),
                ('comprimido', models.BooleanField(default=False, verbose_name='Foi Comprimido')),
                ('enviado_por', models.CharField(max_length=100, verbose_name='Enviado por')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data Upload')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='asaas_sync.asaasclientesyncronizado', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Documento Cliente Asaas',
                'verbose_name_plural': 'Documentos Clientes Asaas',
                'db_table': 'asaas_sync_documentos_clientes',
                'ordering': ['-data_upload'],
            },
        ),
    ]
