# Generated by Django 4.2.7 on 2025-11-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_sync', '0005_documentoclienteasaas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasClienteSyncronizado2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_customer_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Asaas')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência Externa')),
                ('data_criacao_asaas', models.DateTimeField(blank=True, null=True, verbose_name='Criado no Asaas')),
                ('notificacoes_desabilitadas', models.BooleanField(default=False, verbose_name='Notificações Desabilitadas')),
                ('consultor_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consultor Responsável')),
                ('servico_concluido', models.BooleanField(default=False, verbose_name='Serviço Concluído')),
                ('servico_limpa_nome', models.BooleanField(default=False, verbose_name='Limpa Nome')),
                ('servico_retirada_travas', models.BooleanField(default=False, verbose_name='Retirada de Travas')),
                ('servico_restauracao_score', models.BooleanField(default=False, verbose_name='Restauração de Score')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Sincronizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cliente Asaas 2 (Sincronizado)',
                'verbose_name_plural': 'Clientes Asaas 2 (Sincronizados)',
                'db_table': 'asaas_sync_clientes2',
                'ordering': ['-sincronizado_em'],
            },
        ),
        migrations.CreateModel(
            name='AsaasCobrancaSyncronizada2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_payment_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Cobrança Asaas')),
                ('tipo_cobranca', models.CharField(choices=[('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'PIX'), ('UNDEFINED', 'Indefinido')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebida'), ('CONFIRMED', 'Confirmada'), ('OVERDUE', 'Vencida'), ('REFUNDED', 'Estornada'), ('RECEIVED_IN_CASH', 'Recebida em Dinheiro'), ('REFUND_REQUESTED', 'Estorno Solicitado'), ('CHARGEBACK_REQUESTED', 'Chargeback Solicitado'), ('CHARGEBACK_DISPUTE', 'Disputa de Chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Aguardando Reversão de Chargeback'), ('DUNNING_REQUESTED', 'Negativação Solicitada'), ('DUNNING_RECEIVED', 'Negativação Recebida'), ('AWAITING_RISK_ANALYSIS', 'Aguardando Análise de Risco')], db_index=True, max_length=50, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('data_criacao_asaas', models.DateTimeField(blank=True, null=True, verbose_name='Criado no Asaas')),
                ('invoice_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Fatura')),
                ('bank_slip_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Boleto')),
                ('pix_qrcode_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL QR Code PIX')),
                ('pix_copy_paste', models.TextField(blank=True, null=True, verbose_name='PIX Copia e Cola')),
                ('numero_parcela', models.IntegerField(blank=True, null=True, verbose_name='Nº Parcela')),
                ('total_parcelas', models.IntegerField(blank=True, null=True, verbose_name='Total de Parcelas')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência Externa')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Sincronizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='asaas_sync.asaasclientesyncronizado2', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cobrança Asaas 2 (Sincronizada)',
                'verbose_name_plural': 'Cobranças Asaas 2 (Sincronizadas)',
                'db_table': 'asaas_sync_cobrancas2',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.AddIndex(
            model_name='asaasclientesyncronizado2',
            index=models.Index(fields=['cpf_cnpj'], name='asaas_sync__cpf_cnp_7b372a_idx'),
        ),
        migrations.AddIndex(
            model_name='asaasclientesyncronizado2',
            index=models.Index(fields=['asaas_customer_id'], name='asaas_sync__asaas_c_5dfaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='asaasclientesyncronizado2',
            index=models.Index(fields=['-sincronizado_em'], name='asaas_sync__sincron_814f04_idx'),
        ),
        migrations.AddIndex(
            model_name='asaascobrancasyncronizada2',
            index=models.Index(fields=['asaas_payment_id'], name='asaas_sync__asaas_p_017cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='asaascobrancasyncronizada2',
            index=models.Index(fields=['status'], name='asaas_sync__status_420066_idx'),
        ),
        migrations.AddIndex(
            model_name='asaascobrancasyncronizada2',
            index=models.Index(fields=['-data_vencimento'], name='asaas_sync__data_ve_de7316_idx'),
        ),
        migrations.AddIndex(
            model_name='asaascobrancasyncronizada2',
            index=models.Index(fields=['cliente', '-data_vencimento'], name='asaas_sync__cliente_419f7c_idx'),
        ),
    ]
