# Generated by Django 4.2.7 on 2025-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('LIMPA_NOME', 'Limpa Nome'), ('RETIRADA_TRAVAS', 'Retirada de Travas'), ('RECUPERACAO_SCORE', 'Recuperação de Score'), ('COMBINADO', 'Serviço Combinado')], max_length=50)),
                ('descricao', models.TextField()),
                ('prazo_medio', models.IntegerField(help_text='Prazo em dias')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sem_entrada', models.BooleanField(default=False)),
                ('quantidade_parcelas', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequencia_pagamento', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=20)),
                ('forma_entrada', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], max_length=20)),
                ('data_vencimento_primeira', models.DateField()),
                ('data_inicio_servico', models.DateField(blank=True, null=True)),
                ('data_conclusao_prevista', models.DateField(blank=True, null=True)),
                ('dias_para_conclusao', models.IntegerField(default=90)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('limpa_nome', models.BooleanField(default=False)),
                ('retirada_travas', models.BooleanField(default=False)),
                ('recuperacao_score', models.BooleanField(default=False)),
                ('contrato_assinado', models.BooleanField(default=False)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('assinatura_gov', models.BooleanField(default=False)),
                ('liminar_entregue', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('CONTRATO_ASSINADO', 'Contrato Assinado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('INADIMPLENTE', 'Inadimplente'), ('QUEDA_CONTRATO', 'Quebra de Contrato')], default='ORCAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_captador', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_consultor', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.servico')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoPIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_code', models.TextField(blank=True, null=True)),
                ('pix_qr_code_url', models.TextField(blank=True, null=True)),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_pix', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Pagamento PIX',
                'verbose_name_plural': 'Pagamentos PIX',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('id_asaas', models.CharField(blank=True, max_length=100)),
                ('url_boleto', models.URLField(blank=True)),
                ('codigo_barras', models.TextField(blank=True)),
                ('asaas_criado', models.BooleanField(default=False)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['venda', 'numero_parcela'],
                'unique_together': {('venda', 'numero_parcela')},
            },
        ),
    ]
