# Generated by Django 4.2.7 on 2025-10-14 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0010_remove_lead_consultor_lead_atendente'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_risco', models.CharField(choices=[('PRAZO_CURTO_RISCO_ALTO', 'Prazo Curto / Risco Alto'), ('PRAZO_MEDIO_RISCO_MEDIO', 'Prazo Médio / Risco Médio'), ('PRAZO_MEDIO_RISCO_BAIXO', 'Prazo Médio / Risco Médio-Baixo')], max_length=50)),
                ('servico_interesse', models.CharField(choices=[('LIMPA_NOME', 'Limpa Nome'), ('RETIRADA_TRAVAS', 'Retirada de Travas'), ('RECUPERACAO_SCORE', 'Recuperação de Score'), ('RECUPERACAO_LIMPA_NOME', 'Recuperação de Score + Limpa Nome'), ('RETIRADA_TRAVAS_LIMPA_NOME', 'Retirada de Travas + Limpa Nome'), ('RECUPERACAO_RETIRADA_TRAVAS', 'Recuperação de Score + Retirada de Travas'), ('COMPLETO', 'Recuperação de Score + Retirada de Travas + Limpa Nome')], max_length=50)),
                ('valor_proposto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes_levantamento', models.TextField(blank=True, help_text='Informações encontradas no levantamento')),
                ('aceite_cliente', models.BooleanField(default=False, help_text='Cliente aceitou o serviço?')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('CONVERTIDO', 'Convertido em Venda')], default='PENDENTE', max_length=20)),
                ('motivo_recusa', models.TextField(blank=True, help_text='Motivo caso cliente recuse')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_vendas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_vendas', to='marketing.lead')),
                ('motivo_principal', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MOTIVO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_vendas_motivo', to='marketing.motivocontato')),
                ('perfil_emocional', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PERFIL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_vendas_perfil', to='marketing.motivocontato')),
            ],
            options={
                'verbose_name': 'Pré-Venda',
                'verbose_name_plural': 'Pré-Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('RG', 'RG'), ('CRNM', 'CRNM (Estrangeiros)'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('COMPROVANTE_RENDA', 'Comprovante de Renda'), ('OUTROS', 'Outros')], max_length=50)),
                ('arquivo', models.FileField(upload_to='vendas/documentos/%Y/%m/')),
                ('observacoes', models.TextField(blank=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Documento de Venda',
                'verbose_name_plural': 'Documentos de Venda',
                'ordering': ['-data_upload'],
            },
        ),
    ]
