# Generated by Django 4.2.7 on 2025-10-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_prevenda_documentovenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRecusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do motivo de recusa', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada (opcional)')),
                ('ativo', models.BooleanField(default=True, help_text='Motivo está ativo para seleção')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição na lista')),
                ('cor', models.CharField(default='#ffc107', help_text='Cor em hexadecimal para identificação visual', max_length=7)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivo de Recusa',
                'verbose_name_plural': 'Motivos de Recusa',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='prevenda',
            name='motivo_recusa',
            field=models.TextField(blank=True, help_text='Detalhes adicionais sobre a recusa'),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='motivo_recusa_principal',
            field=models.ForeignKey(blank=True, help_text='Motivo principal da recusa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_vendas_recusadas', to='vendas.motivorecusa'),
        ),
    ]
