# Generated by Django 4.2.7 on 2025-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_motivorecusa_alter_prevenda_motivo_recusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='prazo_pagamento_total',
            field=models.IntegerField(blank=True, help_text='Prazo total de pagamento em dias (calculado automaticamente)', null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_conclusao_prevista',
            field=models.DateField(blank=True, help_text='Data calculada automaticamente: data_inicio + dias_para_conclusao', null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_inicio_servico',
            field=models.DateField(blank=True, help_text='Data de início do serviço definida pelo consultor', null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='dias_para_conclusao',
            field=models.IntegerField(default=90, help_text='Dias úteis para conclusão do serviço (escolhido pelo consultor)'),
        ),
    ]
