# Generated by Django 4.2.7 on 2025-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_prazo_pagamento_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevenda',
            name='frequencia_pagamento',
            field=models.CharField(blank=True, default='MENSAL', max_length=20),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
