# Generated by Django 4.2.7 on 2025-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_prevenda_frequencia_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status_compliance_pos_venda',
            field=models.CharField(default='AGUARDANDO_CONFERENCIA', help_text='Status do processo pós-venda no Compliance', max_length=30),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_pagamento_entrada',
            field=models.CharField(default='PENDENTE', help_text='Status do pagamento da entrada: SEM_ENTRADA, PENDENTE, PAGO', max_length=20),
        ),
    ]
