# Generated by Django 4.2.7 on 2025-10-27 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0011_lead_passou_compliance_alter_lead_status'),
        ('vendas', '0006_venda_status_compliance_pos_venda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepescagemLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_CONTATO', 'Em Contato'), ('AGUARDANDO_RESPOSTA', 'Aguardando Resposta'), ('INTERESSADO', 'Interessado - Negociando'), ('CONDICOES_ESPECIAIS', 'Condições Especiais Aplicadas'), ('CONVERTIDO', 'Convertido - Enviado ao Compliance'), ('SEM_INTERESSE', 'Sem Interesse'), ('LEAD_LIXO', 'Lead Lixo')], default='PENDENTE', max_length=30)),
                ('tentativas_contato', models.PositiveIntegerField(default=0)),
                ('condicoes_especiais_aplicadas', models.BooleanField(default=False)),
                ('descricao_condicoes_especiais', models.TextField(blank=True, help_text='Detalhes das condições especiais oferecidas')),
                ('novo_valor_total', models.DecimalField(blank=True, decimal_places=2, help_text='Novo valor total proposto', max_digits=10, null=True)),
                ('novo_valor_entrada', models.DecimalField(blank=True, decimal_places=2, help_text='Novo valor de entrada proposto', max_digits=10, null=True)),
                ('nova_quantidade_parcelas', models.PositiveIntegerField(blank=True, help_text='Nova quantidade de parcelas', null=True)),
                ('novo_valor_parcela', models.DecimalField(blank=True, decimal_places=2, help_text='Novo valor da parcela', max_digits=10, null=True)),
                ('observacoes_consultor_original', models.TextField(blank=True, help_text='Observações do consultor original')),
                ('observacoes_repescagem', models.TextField(blank=True, help_text='Observações da repescagem')),
                ('resposta_lead', models.TextField(blank=True, help_text='Resposta/Feedback do lead')),
                ('proximos_passos', models.TextField(blank=True, help_text='Próximos passos planejados')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_primeiro_contato', models.DateTimeField(blank=True, null=True)),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('consultor_original', models.ForeignKey(help_text='Consultor que atendeu originalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repescagens_originadas', to=settings.AUTH_USER_MODEL)),
                ('consultor_repescagem', models.ForeignKey(blank=True, help_text='Consultor do Comercial 2 responsável pela repescagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repescagens_atendidas', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repescagens', to='marketing.lead')),
                ('motivo_recusa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repescagens', to='vendas.motivorecusa')),
                ('pre_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repescagens', to='vendas.prevenda')),
            ],
            options={
                'verbose_name': 'Repescagem de Lead',
                'verbose_name_plural': 'Repescagens de Leads',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRepescagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interacao', models.CharField(choices=[('LIGACAO', 'Ligação'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('VISITA', 'Visita Presencial'), ('OUTROS', 'Outros')], max_length=20)),
                ('descricao', models.TextField(help_text='Descrição da interação')),
                ('resultado', models.TextField(blank=True, help_text='Resultado/Resposta obtida')),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('repescagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_interacoes', to='vendas.repescagemlead')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Repescagem',
                'verbose_name_plural': 'Históricos de Repescagem',
                'ordering': ['-data_interacao'],
            },
        ),
        migrations.CreateModel(
            name='EstrategiaRepescagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da estratégia', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada da estratégia')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('motivo_recusa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='vendas.motivorecusa')),
            ],
            options={
                'verbose_name': 'Estratégia de Repescagem',
                'verbose_name_plural': 'Estratégias de Repescagem',
                'ordering': ['motivo_recusa', 'ordem', 'titulo'],
            },
        ),
    ]
