# Generated by Django 4.2.7 on 2025-10-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_repescagemlead_historicorepescagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_atual', models.IntegerField(choices=[(0, 'Etapa 1 - Atendimento Iniciado'), (20, 'Etapa 2 - Elaboração e Protocolo'), (40, 'Etapa 3 - Análise e Retorno'), (60, 'Etapa 4 - Monitoramento'), (80, 'Etapa 5 - Conclusão das Atualizações'), (100, 'Etapa 6 - Encerramento Final')], default=0, help_text='Etapa atual do serviço (0, 20, 40, 60, 80, 100)')),
                ('data_etapa_1', models.DateTimeField(blank=True, help_text='Atendimento Iniciado', null=True)),
                ('data_etapa_2', models.DateTimeField(blank=True, help_text='Elaboração e Protocolo', null=True)),
                ('data_etapa_3', models.DateTimeField(blank=True, help_text='Análise e Retorno', null=True)),
                ('data_etapa_4', models.DateTimeField(blank=True, help_text='Monitoramento', null=True)),
                ('data_etapa_5', models.DateTimeField(blank=True, help_text='Conclusão das Atualizações', null=True)),
                ('data_etapa_6', models.DateTimeField(blank=True, help_text='Encerramento Final', null=True)),
                ('observacoes_internas', models.TextField(blank=True, help_text='Observações internas sobre o andamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_servico', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Progresso do Serviço',
                'verbose_name_plural': 'Progressos dos Serviços',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
