# Generated by Django 4.2.7 on 2025-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_progressoservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevenda',
            name='frequencia_pagamento',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=20),
        ),
    ]
