# Generated by Django 4.2.7 on 2025-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_alter_prevenda_frequencia_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente_quer_nf',
            field=models.BooleanField(default=False, help_text='Marcar se cliente solicitou emissão de NF-e', verbose_name='Cliente deseja Nota Fiscal?'),
        ),
        migrations.AddField(
            model_name='venda',
            name='nf_email',
            field=models.EmailField(blank=True, help_text='E-mail para envio da Nota Fiscal (pode ser diferente do e-mail principal)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nf_tipo_pessoa',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], help_text='Tipo de pessoa para emissão da NF', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status_compliance_pos_venda',
            field=models.CharField(choices=[('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência'), ('CONFERENCIA_OK', 'Conferência OK'), ('COLETANDO_DOCUMENTOS', 'Coletando Documentos'), ('DOCUMENTOS_OK', 'Documentos OK'), ('EMITINDO_CONTRATO', 'Emitindo Contrato'), ('CONTRATO_ENVIADO', 'Contrato Enviado'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura'), ('CONTRATO_ASSINADO', 'Contrato Assinado'), ('CONCLUIDO', 'Concluído')], default='AGUARDANDO_CONFERENCIA', help_text='Status do processo pós-venda no Compliance', max_length=30),
        ),
    ]
