# Generated by Django 4.2.7 on 2025-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_venda_cliente_quer_nf_venda_nf_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevenda',
            name='prazo_risco',
            field=models.CharField(blank=True, choices=[('PRAZO_CURTO_RISCO_ALTO', 'Prazo Curto / Risco Alto'), ('PRAZO_MEDIO_RISCO_MEDIO', 'Prazo Médio / Risco Médio'), ('PRAZO_MEDIO_RISCO_BAIXO', 'Prazo Médio / Risco Médio-Baixo')], max_length=50, null=True),
        ),
    ]
