# Generated by Django 4.2.7 on 2025-11-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_prevenda_prazo_risco'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrada', models.IntegerField(help_text='Número sequencial da entrada (1 ou 2)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento da entrada')),
                ('data_pagamento', models.DateTimeField(blank=True, help_text='Data do pagamento confirmado', null=True)),
                ('forma_pagamento', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], default='PIX', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('asaas_payment_id', models.CharField(blank=True, help_text='ID da cobrança no ASAAS', max_length=255, null=True)),
                ('pix_code', models.TextField(blank=True, help_text='Código copia e cola do PIX', null=True)),
                ('pix_qr_code_url', models.TextField(blank=True, help_text='URL da imagem do QR Code', null=True)),
                ('url_boleto', models.URLField(blank=True, help_text='URL do boleto', null=True)),
                ('codigo_barras', models.TextField(blank=True, help_text='Código de barras do boleto', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Entrada de Venda',
                'verbose_name_plural': 'Entradas de Venda',
                'ordering': ['venda', 'numero_entrada'],
                'unique_together': {('venda', 'numero_entrada')},
            },
        ),
    ]
