# Generated by Django 4.2.7 on 2025-11-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_entradavenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaPreVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrada', models.IntegerField(help_text='Número sequencial da entrada (1 ou 2)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento prevista da entrada')),
                ('forma_pagamento', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], default='PIX', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pre_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='vendas.prevenda')),
            ],
            options={
                'verbose_name': 'Entrada de Pré-Venda',
                'verbose_name_plural': 'Entradas de Pré-Venda',
                'ordering': ['pre_venda', 'numero_entrada'],
                'unique_together': {('pre_venda', 'numero_entrada')},
            },
        ),
    ]
