# Generated by Django 4.2.7 on 2025-10-22 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0010_remove_lead_consultor_lead_atendente'),
        ('vendas', '0005_prevenda_frequencia_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('BRONZE', 'Bronze (até R$ 10.000)'), ('PRATA', 'Prata (R$ 10.001 a R$ 50.000)'), ('OURO', 'Ouro (R$ 50.001 a R$ 100.000)'), ('PLATINA', 'Platina (acima de R$ 100.000)'), ('NAO_CLASSIFICADO', 'Não Classificado')], default='NAO_CLASSIFICADO', max_length=20, verbose_name='Classificação do Lead')),
                ('valor_divida_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total da Dívida')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Análise'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado - Aguardando Atribuição'), ('ATRIBUIDO', 'Atribuído ao Consultor'), ('REPROVADO', 'Reprovado'), ('EM_PRE_VENDA', 'Em Pré-Venda')], default='AGUARDANDO', max_length=20, verbose_name='Status da Análise')),
                ('data_atribuicao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atribuição')),
                ('observacoes_analise', models.TextField(blank=True, verbose_name='Observações da Análise')),
                ('motivo_reprovacao', models.TextField(blank=True, verbose_name='Motivo da Reprovação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_compliance_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsável')),
                ('consultor_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_compliance_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Consultor Atribuído')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_compliance', to='marketing.lead')),
                ('pre_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analise_compliance', to='vendas.prevenda', verbose_name='Pré-Venda Associada')),
            ],
            options={
                'verbose_name': 'Análise de Compliance',
                'verbose_name_plural': 'Análises de Compliance',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAnaliseCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='compliance.analisecompliance')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Análise',
                'verbose_name_plural': 'Históricos de Análises',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='GestaoDocumentosPosVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência'), ('CONFERENCIA_OK', 'Conferência OK'), ('COLETANDO_DOCUMENTOS', 'Coletando Documentos'), ('DOCUMENTOS_OK', 'Documentos OK'), ('EMITINDO_CONTRATO', 'Emitindo Contrato'), ('CONTRATO_ENVIADO', 'Contrato Enviado'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura'), ('CONTRATO_ASSINADO', 'Contrato Assinado'), ('CONCLUIDO', 'Concluído')], default='AGUARDANDO_CONFERENCIA', max_length=30, verbose_name='Status')),
                ('cadastro_conferido', models.BooleanField(default=False, verbose_name='Cadastro Conferido')),
                ('data_conferencia_cadastro', models.DateTimeField(blank=True, null=True)),
                ('observacoes_cadastro', models.TextField(blank=True)),
                ('documentos_coletados', models.BooleanField(default=False, verbose_name='Documentos Coletados')),
                ('data_coleta_documentos', models.DateTimeField(blank=True, null=True)),
                ('lista_documentos', models.JSONField(blank=True, default=list, verbose_name='Lista de Documentos')),
                ('contrato_emitido', models.BooleanField(default=False, verbose_name='Contrato Emitido')),
                ('data_emissao_contrato', models.DateTimeField(blank=True, null=True)),
                ('contrato_enviado', models.BooleanField(default=False, verbose_name='Contrato Enviado')),
                ('data_envio_contrato', models.DateTimeField(blank=True, null=True)),
                ('contrato_assinado', models.BooleanField(default=False, verbose_name='Contrato Assinado')),
                ('data_assinatura_contrato', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('analise_compliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestao_pos_venda', to='compliance.analisecompliance', verbose_name='Análise de Compliance')),
                ('pre_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestao_compliance', to='vendas.prevenda', verbose_name='Pré-Venda')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestoes_pos_venda', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Gestão Pós-Venda',
                'verbose_name_plural': 'Gestões Pós-Venda',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
