# Generated by Django 4.2.7 on 2025-10-23 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0006_venda_status_compliance_pos_venda_and_more'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaVendaCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência'), ('CONFERENCIA_OK', 'Conferência OK'), ('COLETANDO_DOCUMENTOS', 'Coletando Documentos'), ('DOCUMENTOS_OK', 'Documentos OK'), ('EMITINDO_CONTRATO', 'Emitindo Contrato'), ('CONTRATO_ENVIADO', 'Contrato Enviado'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura'), ('CONTRATO_ASSINADO', 'Contrato Assinado'), ('CONCLUIDO', 'Concluído')], default='AGUARDANDO_CONFERENCIA', max_length=30)),
                ('status_pagamento_entrada', models.CharField(choices=[('SEM_ENTRADA', 'Sem Entrada'), ('PENDENTE', 'Pagamento Pendente'), ('PAGO', 'Pagamento Pago')], default='PENDENTE', max_length=20)),
                ('dados_cliente_conferidos', models.BooleanField(default=False)),
                ('nome_ok', models.BooleanField(default=False)),
                ('cpf_ok', models.BooleanField(default=False)),
                ('telefone_ok', models.BooleanField(default=False)),
                ('email_ok', models.BooleanField(default=False)),
                ('endereco_ok', models.BooleanField(default=False)),
                ('dados_venda_conferidos', models.BooleanField(default=False)),
                ('servico_ok', models.BooleanField(default=False)),
                ('valores_ok', models.BooleanField(default=False)),
                ('parcelas_ok', models.BooleanField(default=False)),
                ('forma_pagamento_ok', models.BooleanField(default=False)),
                ('datas_ok', models.BooleanField(default=False)),
                ('observacoes_conferencia', models.TextField(blank=True, verbose_name='Observações da Conferência')),
                ('pendencias', models.TextField(blank=True, verbose_name='Pendências Identificadas')),
                ('motivo_reprovacao', models.TextField(blank=True, verbose_name='Motivo da Reprovação')),
                ('data_inicio_conferencia', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao_conferencia', models.DateTimeField(blank=True, null=True)),
                ('data_reprovacao', models.DateTimeField(blank=True, null=True)),
                ('todos_documentos_ok', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('historico', models.JSONField(blank=True, default=list, verbose_name='Histórico de Ações')),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conferencia_compliance', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Conferência de Venda',
                'verbose_name_plural': 'Conferências de Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ContratoCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(blank=True, max_length=50, unique=True)),
                ('template_utilizado', models.CharField(blank=True, max_length=100)),
                ('arquivo_gerado', models.FileField(blank=True, null=True, upload_to='contratos/%Y/%m/', verbose_name='Arquivo do Contrato Gerado')),
                ('data_geracao', models.DateTimeField(blank=True, null=True)),
                ('enviado_whatsapp', models.BooleanField(default=False)),
                ('data_envio_whatsapp', models.DateTimeField(blank=True, null=True)),
                ('numero_whatsapp', models.CharField(blank=True, max_length=20)),
                ('enviado_email', models.BooleanField(default=False)),
                ('data_envio_email', models.DateTimeField(blank=True, null=True)),
                ('email_destino', models.EmailField(blank=True, max_length=254)),
                ('tipo_assinatura', models.CharField(blank=True, choices=[('GOV_BR', 'Gov.br (Digital)'), ('MANUAL', 'Manual (Upload)')], max_length=20, null=True)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='contratos/assinados/%Y/%m/', verbose_name='Arquivo do Contrato Assinado')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('link_assinatura_gov', models.URLField(blank=True, verbose_name='Link Assinatura Gov.br')),
                ('validado', models.BooleanField(default=False)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_GERACAO', 'Aguardando Geração'), ('GERADO', 'Gerado'), ('ENVIADO_WHATSAPP', 'Enviado por WhatsApp'), ('ENVIADO_EMAIL', 'Enviado por Email'), ('ENVIADO_AMBOS', 'Enviado por WhatsApp e Email'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura'), ('ASSINADO_GOV', 'Assinado via Gov.br'), ('ASSINADO_MANUAL', 'Assinado Manualmente'), ('VALIDADO', 'Validado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_GERACAO', max_length=30)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('historico_status', models.JSONField(blank=True, default=list, verbose_name='Histórico de Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conferencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='compliance.conferenciavendacompliance')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_gerados_compliance', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_validados_compliance', to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_compliance', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVendaCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG_FRENTE', 'RG - Frente'), ('RG_VERSO', 'RG - Verso'), ('CPF', 'CPF'), ('COMP_RESIDENCIA', 'Comprovante de Residência'), ('SELFIE_DOC', 'Selfie com Documento'), ('CERTIDAO_CASAMENTO', 'Certidão de Casamento'), ('CERTIDAO_DIVORCIO', 'Certidão de Divórcio'), ('DECLARACAO_UNIAO', 'Declaração de União Estável'), ('PROCURACAO', 'Procuração'), ('COMP_RENDA', 'Comprovante de Renda'), ('OUTRO', 'Outro')], max_length=30)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_vendas/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Upload'), ('RECEBIDO', 'Recebido - Aguardando Validação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Documento Obrigatório')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('data_upload', models.DateTimeField(blank=True, null=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='compliance.conferenciavendacompliance')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento da Venda',
                'verbose_name_plural': 'Documentos das Vendas',
                'ordering': ['obrigatorio', 'tipo'],
                'unique_together': {('conferencia', 'tipo')},
            },
        ),
    ]
