# Generated by Django 4.2.7 on 2025-10-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_conferenciavendacompliance_contratocompliance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciavendacompliance',
            name='estado_civil_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conferenciavendacompliance',
            name='nacionalidade_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conferenciavendacompliance',
            name='profissao_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conferenciavendacompliance',
            name='rg_ok',
            field=models.BooleanField(default=False),
        ),
    ]
