# Generated by Django 4.2.7 on 2025-11-03 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0003_conferenciavendacompliance_estado_civil_ok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLevantamentoCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RELATORIO_COMPLETO', 'Relatório Completo'), ('EXTRATO_BANCARIO', 'Extrato Bancário'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('EMPRESTIMO', 'Empréstimo'), ('FINANCIAMENTO', 'Financiamento'), ('OUTROS', 'Outros')], default='RELATORIO_COMPLETO', max_length=30, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='compliance/levantamentos/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_levantamento', to='compliance.analisecompliance', verbose_name='Análise de Compliance')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_levantamento_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
            ],
            options={
                'verbose_name': 'Documento de Levantamento',
                'verbose_name_plural': 'Documentos de Levantamento',
                'ordering': ['-data_upload'],
            },
        ),
    ]
