# Generated by Django 4.2.7 on 2025-11-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_documentolevantamentocompliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolevantamentocompliance',
            name='tipo',
            field=models.CharField(choices=[('RELATORIO_COMPLETO', 'Levantamento'), ('EXTRATO_BANCARIO', 'Extrato Bancário'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('EMPRESTIMO', 'Empréstimo'), ('FINANCIAMENTO', 'Financiamento'), ('OUTROS', 'Outros')], default='RELATORIO_COMPLETO', max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
