# Generated by Django 4.2.7 on 2025-10-11 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0008_lead_fez_levantamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='marketing.lead')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comissão de Lead',
                'verbose_name_plural': 'Comissões de Leads',
                'unique_together': {('lead', 'usuario')},
            },
        ),
    ]
