# Generated by Django 4.2.7 on 2025-10-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissaolead',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
