# Generated by Django 4.2.7 on 2025-10-13 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_lead_fez_levantamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comissoes', '0002_alter_comissaolead_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comissaolead',
            old_name='usuario',
            new_name='atendente',
        ),
        migrations.AlterUniqueTogether(
            name='comissaolead',
            unique_together={('lead', 'atendente')},
        ),
    ]
