# Generated by Django 4.2.7 on 2025-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0003_rename_usuario_comissaolead_atendente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissaolead',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Comissão de Lead', 'verbose_name_plural': 'Comissões de Leads'},
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data do pagamento da comissão', null=True),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a comissão'),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='pago',
            field=models.BooleanField(default=False, help_text='Indica se a comissão já foi paga ao atendente'),
        ),
        migrations.AlterField(
            model_name='comissaolead',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
