# Generated by Django 4.2.7 on 2025-11-05 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_prevenda_prazo_risco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comissoes', '0004_alter_comissaolead_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atendente', 'Atendente'), ('consultor', 'Consultor'), ('captador', 'Captador')], max_length=20)),
                ('competencia', models.DateField(help_text='Mês/ano de referência')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade_comissoes', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Comissão',
                'verbose_name_plural': 'Pagamentos de Comissões',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoConsultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da comissão', max_digits=10)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual aplicado sobre a venda', max_digits=5)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('competencia', models.DateField(help_text='Mês/ano de referência para pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento da comissão', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a comissão')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_consultor', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_consultor', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Comissão de Consultor',
                'verbose_name_plural': 'Comissões de Consultores',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['consultor', 'status'], name='comissoes_c_consult_cd94c2_idx'), models.Index(fields=['competencia', 'status'], name='comissoes_c_compete_3a71c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComissaoCaptador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da comissão', max_digits=10)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual aplicado sobre a venda', max_digits=5)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('competencia', models.DateField(help_text='Mês/ano de referência para pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento da comissão', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a comissão')),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_captador', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_captador', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Comissão de Captador',
                'verbose_name_plural': 'Comissões de Captadores',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['captador', 'status'], name='comissoes_c_captado_67d583_idx'), models.Index(fields=['competencia', 'status'], name='comissoes_c_compete_212ade_idx')],
            },
        ),
    ]
