# Generated by Django 4.2.7 on 2025-11-05 22:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_prevenda_prazo_risco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comissoes', '0005_update_pagamento_comissao_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissaolead',
            name='pago',
        ),
        migrations.AddField(
            model_name='comissaocaptador',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_captador_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaocaptador',
            name='data_autorizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comissaocaptador',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_captador_pagas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaocaptador',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_captador', to='vendas.parcela'),
        ),
        migrations.AddField(
            model_name='comissaocaptador',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor da venda/parcela', max_digits=10),
        ),
        migrations.AddField(
            model_name='comissaoconsultor',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_consultor_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaoconsultor',
            name='data_autorizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comissaoconsultor',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_consultor_pagas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaoconsultor',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_consultor', to='vendas.parcela'),
        ),
        migrations.AddField(
            model_name='comissaoconsultor',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor da venda/parcela', max_digits=10),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='competencia',
            field=models.DateField(blank=True, help_text='Mês/ano de referência para pagamento', null=True),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='data_autorizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_pagas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaolead',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('AUTORIZADO', 'Autorizado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='comissaocaptador',
            name='competencia',
            field=models.DateField(blank=True, help_text='Mês/ano de referência para pagamento', null=True),
        ),
        migrations.AlterField(
            model_name='comissaocaptador',
            name='percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual aplicado sobre a venda', max_digits=5),
        ),
        migrations.AlterField(
            model_name='comissaocaptador',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('AUTORIZADO', 'Autorizado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='comissaoconsultor',
            name='competencia',
            field=models.DateField(blank=True, help_text='Mês/ano de referência para pagamento', null=True),
        ),
        migrations.AlterField(
            model_name='comissaoconsultor',
            name='percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual aplicado sobre a venda', max_digits=5),
        ),
        migrations.AlterField(
            model_name='comissaoconsultor',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('AUTORIZADO', 'Autorizado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comissaolead',
            index=models.Index(fields=['atendente', 'status'], name='comissoes_c_atenden_a7d89a_idx'),
        ),
        migrations.AddIndex(
            model_name='comissaolead',
            index=models.Index(fields=['competencia', 'status'], name='comissoes_c_compete_c2fb8d_idx'),
        ),
    ]
